<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="PhoenixWeb._Default" %>

<%--Author: Bobby Vocque--%>

<%--used the default CSS config generated by Visual Studio--%>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div class="jumbotron">
        <h1>Phoenix Computers</h1>
        <h3>Owner: Bobby Vocque</h3>
        <p class="lead">The header and first column of the product table below are populated using arrays.  The remaining data shown is employed via a list collection.
        <p></p>
    </div>

    <div class="row">
        <center>

        <table id="dynamicTable"  style="width:90%;" >

            <asp:PlaceHolder ID="placeholder" runat="server"></asp:PlaceHolder>

        </table>
            </center>
     </div>
        

</asp:Content>
